# Generated by Django 5.1.1 on 2024-10-04 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addnote',
            name='username',
            field=models.TextField(),
        ),
    ]
